// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abodicrbjknkmqgdwhts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFib2RpY3Jiamtua21xZ2R3aHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTcyMjYsImV4cCI6MjA1OTY3MzIyNn0.p34Gg2aI2eYPXThLmZuD6mRsYkuBXLuyGGr9a1riznY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);